# Generated by Django 5.1.3 on 2025-01-18 05:15

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', max_length=100, unique=True),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reply_points',
        ),
        migrations.AddField(
            model_name='post',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='createdat', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='DownvoteCount',
            field=models.IntegerField(db_column='downvotecount', default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='PostID',
            field=models.AutoField(db_column='postid', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='UpvoteCount',
            field=models.IntegerField(db_column='upvotecount', default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='UserID',
            field=models.ForeignKey(db_column='userid', default=1, on_delete=django.db.models.deletion.CASCADE, to='opinions_app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ChatID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='chatid', null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='DisplayName',
            field=models.CharField(db_column='displayname', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='followers', null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='UserID',
            field=models.AutoField(db_column='userid', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='isInfluencer',
            field=models.BooleanField(db_column='isinfluencer', default=False),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('ReplyID', models.AutoField(db_column='replyid', primary_key=True, serialize=False)),
                ('ReplyText', models.TextField(db_column='replytext')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('PostID', models.ForeignKey(db_column='postid', on_delete=django.db.models.deletion.CASCADE, to='opinions_app.post')),
                ('UserID', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='opinions_app.user')),
            ],
            options={
                'db_table': 'replies',
            },
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(db_column='email', default='email@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(db_column='password', default='hashed_password', max_length=255),
            preserve_default=False,
        ),
    ]
